### ISSUE TITLE
Convert YML to JSON doesn't do anything

### ISSUE THREAD

**Issue by kavehv** [tuxtina/json2yaml#1]
It doesn't seem to spit anything out to any debug console either.  It just continues to show me my yml file.

**Comment by tuxtina** [comment]
The extension only works on the selection, so if nothing is selected, nothing happens 😟 I've been meaning to fix that for a while, thanks for reminding me. Should be fixed in 6658380025c71f0fb0caca26f6ff630f8d035535 (v0.2.0). Please let me know if you're still having trouble.

**Comment by kavehv** [comment]
Aha...thanks, I thought I was missing something obvious.  Works great.  Just one enhancement request I filed as issue #2.
