### ISSUE TITLE
Could not parse the selection as JSON/YAML.

### ISSUE THREAD

**Issue by iamkarlson** [tuxtina/json2yaml#5]
That error occurs for all the scenarios. How can I get any logs to further diagnose the issue?

**Comment by tuxtina** [comment]
[edited regarding logs]

Do you have a screenshot showing an example of a text that fails to convert, the current editor selection, and the lower right corner of the editor window (where it shows the text encoding etc.)? Which version of VScode are you using?

You can see the actual parse error (if any) in Help > Developer Tools, there click the Console tab.

**Comment by iamkarlson** [comment]
Yes, thanks, console tab is enough!

**Comment by gsterg** [comment]
I see this closed, is this fixed ? I am always getting this error regardless the yaml I enter. Trying to do yaml to json

**Comment by tuxtina** [comment]
It's definitely not something I have been able to reproduce yet. If you have any of the following info that might help narrow down the issue:

> Do you have a screenshot showing an example of a text that fails to convert, the current editor selection, and the lower right corner of the editor window (where it shows the text encoding etc.)? Which version of VScode are you using?
> 
> You can see the actual parse error (if any) in Help > Developer Tools, there click the Console tab.

**Comment by iamkarlson** [comment]
@gsterg It wasn't an issue with plugin. If you could open developer console in VSCode you can probably see errors more detailed.

**Comment by gsterg** [comment]
Hello, will send you details about versions and screenshots later tonight.

Regards


On Fri, Sep 28, 2018, 5:16 AM Georgy Grigoryev <notifications@github.com<mailto:notifications@github.com>> wrote:

@gsterg<https://github.com/gsterg> It wasn't an issue with plugin. If you could open developer console in VSCode you can probably see errors more detailed.
